cfg_type: dev
pg_url: postgres://postgres:postgres@postgres/ads-service?sslmode=disable
migrations_dir: file://migrations
http_server_address: 0.0.0.0:8080
auth_grpc:
  address: grpc-server:44044
  secret_key: secret123
  app_id: 1